[tool.poetry]
name = "src"
version = "0.1.0"
description = "Search for vulnerabilities by scanning through GitHub issues."
authors = ["Adam Goldschmidt <adamgold7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.22.0"
aiohttp = "^3.6.2"
click = "^7.0"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"
pytest = "^5.3.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

